backend = "xrender";
vsync = true;
inactive-opacity=0.85
active-opacity=1
inactive-opacity-override=true
blur-background-frame=false
frame-opacity=1
fading=true
fade-in-step=0.028
fade-out-step=0.03
fade-delta=10
inactive-dim=0
corner-radius=0
#rules = (
#{match = "name = 'dwm'"; opacity=0.1;}
#)
#blur:
#{
#  method = "kernel";
#  size = 10;
#  strength = 9;
#};
#shadow=true
#shadow-opacity=1
animations=(
{
  triggers = ["close"];
  preset="slide-out";
  direction = "right";
},
{
  triggers = ["open"];
  preset="appear";
  scale = 0.2;
},
{
  triggers = ["geometry"];
  preset="geometry-change";
}
)

