#!/usr/bin/env sh
case $BLOCK_BUTTON in
  1) "$TERMINAL" -e sh -ic "echo $packages; echo Press Enter to Close; read";;
  2) "$TERMINAL" -e sh -c "vim ~/.config/dwmblocks-async/scripts/packagestoupdate";;
esac
packages=$(yay -Qu)
lines=$(printf '%s' "$packages" | wc -l)
echo "󰏗 $lines"
