set-option -g prefix C-b
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"
set -g mouse on

bind-key v split-window -h
bind-key h split-window -v
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

bind -n C-S-Left previous-window
bind -n C-S-Right next-window
bind-key y set-window-option synchronize-panes\; display-message "Sync toggled"

# Status Bar
set -g status-justify left
set -g status-bg black
set -g status-fg white
set -g status-right '#{host} %H:%M-%B%d-%Y'
set -g status-left '[#[bold]#S#[nobold]]'
set -g base-index 1
set-window-option -g automatic-rename
set-window-option -g pane-base-index 1
setw -g monitor-activity off
setw -g monitor-silence 0
set -g window-status-activity-style fg=blue,bg=black
set -g window-status-current-style fg=green,bg=black
set -g window-status-current-format " #I:#W "
set -g window-status-format " #I:#W "
set -g monitor-bell on
set -g status-justify centre
set -g window-status-bell-style fg=black,bg=green
setw -g mode-keys vi
set -g set-clipboard on
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"

set-option -g default-terminal "xterm-256color"
