export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export FZF_DEFAULT_OPTS_FILE="${HOME}/.config/fzf/fzfrc"
export BROWSER="librewolf"
export MANPAGER="sh -c 'col -bx | /usr/bin/bat --language=man -p'"
export MANROFFOPT="-c"
export MPD_HOST="localhost"
export MPD_PORT="6600"
export TERMINAL="alacritty"
export EXPLORER="yazi"
export EDITOR="nvim"
export PATH="/home/xor/installedApps/bin:$PATH"
