[server]
# asciinema server URL
# If you run your own instance of asciinema server then set its address here
# It can also be overridden by setting ASCIINEMA_SERVER_URL environment variable
url = "https://asciinema.org"

[session]
# This section applies to commands that start a new shell session, i.e. `rec`,
# `stream` and `session`.

command = "$SHELL -l"
capture_input = true
capture_env = "SHELL,TERM,USER"
idle_time_limit = 1
pause_key = "^p"
add_marker_key = "^x"
prefix_key = "^a"

[playback]
speed = 1
idle_time_limit = 1
pause_key = "p"
step_key = "."
next_marker_key = "m"

[notifications]
enabled = true
command = 'notify-send "$TEXT"'
