font_size 14
font_family      family='IosevkaTerm Nerd Font Mono' style=Regular features='+dlig cv01=3 cv02=1 cv03=1 cv04=6 cv06=3 cv10=2'
bold_font        family='IosevkaTerm Nerd Font Mono' style=Bold features=+dlig
italic_font      family='IosevkaTerm Nerd Font Mono' features='+dlig cv01=3 cv02=0 cv03=0 cv04=6 cv06=3 cv10=2 cv11=9 cv12=8 cv41=39 cv42=13 cv44=11 cv45=1 cv46=27'
bold_italic_font auto
