map ctrl+f2 detach_window
map ctrl+shift+p nth_window -1
enabled_layouts *
window_resize_step_cells 2
window_resize_step_lines 2
window_border_width 0.5pt
window_margin_width 0
single_window_margin_width -1
draw_minimal_border yes
draw_window_borders_for_single_window no
hide_window_decorations yes
