general {
  grab_focus = true # Whether to force a full keyboard focus grab.
}
cache {
  enabled = true # Controls whether modules keep a cache of often used entries. That history is stored on your disk, in plain text, in `~/.local/share/hyprlauncher`.
}
finders {
  default_finder = desktop # Controls the default finder used.
  desktop_prefix = # Prefix for the desktop finder to be used.
  unicode_prefix = . # Prefix for the unicode finder to be used.
  math_prefix = = # Prefix for the math finder to be used.
  font_prefix = ' # Prefix for the font finder to be used.
  desktop_launch_prefix = # Launch prefix for each desktop app, e.g. `uwsw app -- `.
  desktop_icons = true # Whether to enable desktop icons in the results.
}
ui {
  window_size = 400 260 # The size of the launcher
}
