splash = false # Enable rendering of the hyprland splash over the wallpaper
splash_offset = 20 # How far up should the splash be displayed
splash_opacity = 0.8 # How opaque the splash is
ipc = true # Whether to enable IPC
wallpaper {
  monitor = # Monitor to display this wallpaper on. If empty, will use this wallpaper as a fallback
  path = ~/Pictures/walls # Path to an image file or a directory containing image files
  fit_mode = cover # Determines how to display the image. Optional and defaults to `cover`
  timeout = 900 # Timeout between each wallpaper change (in seconds, if `path` is a directory). Optional and defaults to 30 seconds
  order = random # Determines the order to display images when a directory is passed to the `path` option. Optional, currently only supported value is `random`
  recursive = true # Whether to scan subdirectories recursively when `path` is a directory. Optional and defaults to false
}
