general {
  lock_cmd = pidof hyprlock || hyprlock # Command to run when receiving a dbus lock event (e.g. `loginctl lock-session`)
  unlock_cmd = loginctl unlock-session # Command to run when receiving a dbus unlock event (e.g. `loginctl unlock-session`)
  on_lock_cmd = # Command to run when the session gets locked by a lock screen app.
  on_unlock_cmd = # Command to run when the session gets unlocked by a lock screen app.
  before_sleep_cmd = loginctl lock-session # Command to run when receiving a dbus prepare_sleep event.
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Command to run when receiving a dbus post prepare_sleep event.
  ignore_dbus_inhibit = false # Whether to ignore dbus-sent idle inhibit events (e.g. from Firefox)
  ignore_systemd_inhibit = false # Whether to ignore `systemd-inhinit --what=idle` inhibitors.
  ignore_wayland_inhibit = false # Whether to ignore Wayland protocol idle inhibitors.
  inhibit_sleep = 2 # Sleep inhibition mode: 0: disable, 1: normal, 2: auto, 3: lock notify
}

listener {
  timeout = 600 # 10 minutes
  on-timeout = brightnessctl --save set 20%; hyprctl notify 1 10000 "rgb(ff0000)" "fontsize:24 Locking after 20 minutes of inactivity"
  on-resume = brightnessctl --restore
  ignore_inhibit = false
}

listener {
  timeout = 1800
  on-timeout = loginctl lock-session; hyprctl notify 1 10000 "rgb(ff0000)" "fontsize:24 Turning off display after 15 more minutes of inactivity"
  ignore_inhibit = false
}

listener {
  timeout = 2700
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable"})'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
  ignore_inhibit = false
}

listener {
  timeout = 3000
  on-timeout = systemctl suspend
  ignore_inhibit = false
}
