return {
  {
    "folke/tokyonight.nvim",
    enabled=true,
    lazy=false,
    priority=1000,
    opts={
      style="moon",
      light_style="day",
      transparent=false,
      terminal_colors=true,
      styles={
        comments={italic=true,},
        keywords={italic=true,},
        functions={},
        variables={},
        sidebars="dark",
        floats="dark",
      },
      day_brightness=0.3,
      dim_inactive=false,
      lualine_bold=false,
      on_colors=function(colors) end,
      on_highlights=function(highlights, colors) end,
      cache=true,
      plugins={
        all=package.loaded.lazy==nil,
        auto=true,
      }
    },
  },
  {
    "ellisonleao/gruvbox.nvim",
    enabled=true,
    priority=1000,
    lazy=false,
    opts={
      terminal_colors=true,
      undercurl=true,
      underline=true,
      bold=true,
      italic={
        strings=true,
        emphasis=true,
        comments=true,
        folds=true,
      },
      strikethrough=true,
      invert_selection=false,
      invert_tabline=false,
      inverse=true,
      contrast="",
      palette_overrides={},
      overrides={},
      dim_inactive=false,
      transparent_mode=false,
    },
  },
  {
    "EdenEast/nightfox.nvim",
    enabled=true,
    opts={
      compile_path = vim.fn.stdpath("cache") .. "/nightfox",
      compile_file_suffix = "_compiled",
      transparent = false,
      terminal_colors = true,
      dim_inactive = false,
      module_default = true,
      colorblind = {
        enable = false,
        simulate_only = false,
        severity = {
          protan = 0,
          deutan = 0,
          tritan = 0,
        },
      },
      styles = {
        comments = "NONE",
        conditionals = "NONE",
        constants = "NONE",
        functions = "NONE",
        keywords = "NONE",
        numbers = "NONE",
        operators = "NONE",
        strings = "NONE",
        types = "NONE",
        variables = "NONE",
      },
      inverse = {
        match_paren = false,
        visual = false,
        search = false,
      },
      modules = {},
    },
    palettes = {},
    specs = {},
    groups = {},
  },
}
